baseURL = "https://www.doniacld.com"
languageCode = "en-us"
title = "Donia Chaiehloudj"
copyright = "Donia Chaiehloudj"

# Using custom layouts (no external theme required)
# theme = ""

# Content settings
summaryLength = 50
enableRobotsTXT = true
enableEmoji = true

# Pagination
[pagination]
  pagerSize = 10

# Taxonomies
[taxonomies]
  tag = "tags"

# Main navigation
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1

[[menu.main]]
name = "Talks"
url = "/talks/"
weight = 2

[[menu.main]]
name = "Podcasts"
url = "/podcasts/"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 4

[[menu.main]]
name = "Book"
url = "/book/"
weight = 5

[[menu.main]]
name = "About"
url = "/about/"
weight = 6

# Markup settings
[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe = true

# Site parameters
[params]
  description = "Software Developer | Go Enthusiast | Speaker | Community Builder"
  author = "Donia Chaiehloudj"
  
  # Homepage hero
  tagline = "Software Developer crafting Go applications and building tech communities"
  focusAreas = ["Go & TinyGo", "Cloud Native", "Community Building"]
  
  # Social links
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/doniacld"
    icon = "github"
  [[params.social]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/donia-chaiehloudj"
    icon = "linkedin"
  [[params.social]]
    name = "Bluesky"
    url = "https://bsky.app/profile/doniacld.bsky.social"
    icon = "bluesky"
  [[params.social]]
    name = "Mastodon"
    url = "https://hachyderm.io/@doniacld"
    icon = "mastodon"
  [[params.social]]
    name = "Medium"
    url = "https://doniacld.medium.com/"
    icon = "medium"
  [[params.social]]
    name = "RSS"
    url = "/index.xml"
    icon = "rss"

  # Homepage sections
  [params.homepage]
    showLatestPosts = 5

# Permalinks
[permalinks]
  blog = "/blog/:contentbasename/"

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
